"""Add acknowledgment and assignee tracking fields

Revision ID: 0002
Revises: 0001
Create Date: 2024-01-02 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('jira_assignee', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('jira_assignee_email', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'resolved_by')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'jira_assignee_email')
    op.drop_column('alerts', 'jira_assignee')
    # ### end Alembic commands ###
